//
//  AgentPlan.swift
//  SwiftAgentKit
//
//  Planning module — generalized from planner/executor agent patterns.
//
//  The planner makes a separate LLM call (without tools) to generate
//  a structured plan, then tracks progress as the ReAct loop executes tools.
//  This generalizes that pattern.
//

import Foundation
import LLMProviderKit

/// A step in an agent execution plan.
///
public struct AgentPlanStep: Sendable, Identifiable, Codable, Equatable {

    public let id: String
    public var step: String
    public var status: AgentPlanStepStatus
    public var targets: [String]  // file/folder/resource names extracted from step text

    public init(id: String = UUID().uuidString, step: String, status: AgentPlanStepStatus = .pending, targets: [String] = []) {
        self.id = id
        self.step = step
        self.status = status
        self.targets = targets
    }
}

/// Status of a plan step.
///
public enum AgentPlanStepStatus: String, Sendable, Codable, Equatable, CaseIterable {

    case pending
    case inProgress
    case completed
    case verified
    case failed
}

/// An execution plan generated by the planner.
///
public struct AgentPlan: Sendable, Equatable {

    public var steps: [AgentPlanStep]

    public init(steps: [AgentPlanStep] = []) {
        self.steps = steps
    }

    /// Whether there are any pending or in-progress steps.
    public var hasPendingSteps: Bool {
        steps.contains { $0.status == .pending || $0.status == .inProgress }
    }

    /// Get all pending steps.
    public var pendingSteps: [AgentPlanStep] {
        steps.filter { $0.status == .pending || $0.status == .inProgress }
    }

    /// Count completed steps.
    public var completedCount: Int {
        steps.filter { $0.status == .completed || $0.status == .verified }.count
    }

    /// Progress as a fraction (0.0 to 1.0).
    public var progress: Double {
        guard !steps.isEmpty else { return 1.0 }
        return Double(completedCount) / Double(steps.count)
    }
}

// MARK: - Planner Protocol

/// A planner generates an execution plan from a user query.
///
/// The default implementation (`LLMPlanner`) makes a separate LLM call
/// to generate a plan. Apps can conform to this protocol to implement
/// custom planning strategies.
///
public protocol AgentPlanner: Sendable {

    /// Whether planning should be used for the given query.
    func shouldPlan(for query: String) -> Bool

    /// Generate a plan for the query.
    func generatePlan(for query: String, systemPrompt: String?) async throws -> AgentPlan

    /// Update plan progress after a tool execution.
    func updateProgress(plan: inout AgentPlan, toolCall: AgentToolCall, result: AgentToolResult)
}

// MARK: - Default LLM Planner

/// A planner that uses an LLM call to generate a structured plan.
///
/// This uses a planner/executor pattern: make a separate LLM call
/// (without tools) asking the model to return JSON `{"steps": [...]}`,
/// then parse it into an `AgentPlan`.
///
public final class LLMPlanner: AgentPlanner, @unchecked Sendable {

    public var plannerSystemPrompt: String
    public var shouldPlanThreshold: (String) -> Bool

    private let plannerProvider: any LLMProvider
    private let plannerModel: String

    public init(
        provider: any LLMProvider,
        model: String? = nil,
        systemPrompt: String? = nil,
        shouldPlanThreshold: @escaping (String) -> Bool = { query in
            // Default: plan for queries that look like multi-step tasks
            let indicators = ["create", "build", "set up", "organize", "convert", "transform", "analyze", "refactor"]
            let lowerQuery = query.lowercased()
            return indicators.contains { lowerQuery.contains($0) } && query.count > 20
        }
    ) {
        self.plannerProvider = provider
        self.plannerModel = model ?? provider.configuration.defaultModel ?? ""
        self.shouldPlanThreshold = shouldPlanThreshold
        self.plannerSystemPrompt = systemPrompt ?? Self.defaultPlannerPrompt
    }

    public func shouldPlan(for query: String) -> Bool {
        shouldPlanThreshold(query)
    }

    public func generatePlan(for query: String, systemPrompt: String? = nil) async throws -> AgentPlan {
        let prompt = systemPrompt ?? plannerSystemPrompt
        let request = LLMRequest(
            model: plannerModel,
            messages: [
                .system(prompt),
                .user("Generate a step-by-step plan for this task. Return ONLY valid JSON.\n\nTask: \(query)")
            ],
            temperature: 0.0
        )

        let response = try await plannerProvider.complete(request)
        let steps = try Self.parsePlanSteps(from: response.text)
        return AgentPlan(steps: steps.map { AgentPlanStep(step: $0) })
    }

    public func updateProgress(plan: inout AgentPlan, toolCall: AgentToolCall, result: AgentToolResult) {
        // Match tool call to plan steps by target keywords
        for index in plan.steps.indices {
            let step = plan.steps[index]
            if step.status == .completed || step.status == .verified { continue }

            // Simple matching: check if any target appears in the tool name or result
            let matchFound = step.targets.contains { target in
                toolCall.name.lowercased().contains(target.lowercased()) ||
                result.result.lowercased().contains(target.lowercased())
            }

            if matchFound {
                plan.steps[index].status = result.isError ? .failed : .completed
            }
        }
    }

    // MARK: - Parsing

    /// Parse plan steps from LLM output with tolerant JSON extraction.
    public static func parsePlanSteps(from text: String) throws -> [String] {
        // Try to extract JSON object with "steps" array
        let jsonStr = extractJSONObject(from: text) ?? text

        guard let data = jsonStr.data(using: .utf8),
              let parsed = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let steps = parsed["steps"] as? [Any] else {
            // Fallback: split by newlines and strip numbering
            return text
                .split(separator: "\n")
                .map { String($0).trimmingCharacters(in: .whitespacesAndNewlines) }
                .filter { !$0.isEmpty && !$0.allSatisfy({ $0.isNumber || $0 == "." || $0 == " " }) }
                .map { step in
                    // Strip leading "1. " or "- " prefixes
                    if let dotIdx = step.firstIndex(of: ".") {
                        let prefix = step[..<dotIdx]
                        if prefix.allSatisfy({ $0.isNumber || $0 == " " }) {
                            return String(step[step.index(after: dotIdx)...]).trimmingCharacters(in: .whitespaces)
                        }
                    }
                    if step.hasPrefix("- ") { return String(step.dropFirst(2)) }
                    if step.hasPrefix("• ") { return String(step.dropFirst(2)) }
                    return step
                }
        }

        return steps.compactMap { step in
            if let str = step as? String { return str }
            if let dict = step as? [String: Any], let desc = dict["step"] as? String ?? dict["description"] as? String { return desc }
            return nil
        }
    }

    /// Extract the first complete JSON object from a string (brace matching).
    /// Handles markdown code fences and surrounding prose.
    /// Generalized from tolerant structured-output parsing patterns.
    public static func extractJSONObject(from raw: String) -> String? {
        // Strip markdown code fences
        var text = raw
        if text.contains("```") {
            if let startRange = text.range(of: "```json\n") {
                text = String(text[startRange.upperBound...])
            } else if let startRange = text.range(of: "```\n") {
                text = String(text[startRange.upperBound...])
            }
            if let endRange = text.range(of: "```") {
                text = String(text[..<endRange.lowerBound])
            }
        }

        guard let startIdx = text.firstIndex(of: "{") else { return nil }
        var depth = 0
        var inString = false
        var escape = false
        var idx = startIdx

        while idx < text.endIndex {
            let char = text[idx]

            if escape {
                escape = false
                idx = text.index(after: idx)
                continue
            }

            if char == "\\" {
                escape = true
                idx = text.index(after: idx)
                continue
            }

            if char == "\"" {
                inString.toggle()
            }

            if !inString {
                if char == "{" { depth += 1 }
                if char == "}" {
                    depth -= 1
                    if depth == 0 {
                        return String(text[startIdx...idx])
                    }
                }
            }

            idx = text.index(after: idx)
        }

        return nil
    }

    // MARK: - Default Prompt

    public static let defaultPlannerPrompt = """
    You are a task planner. Your job is to break down the user's task into clear, \
    actionable steps. Return ONLY a valid JSON object with this exact format:

    {"steps": ["Step 1 description", "Step 2 description", "Step 3 description"]}

    Rules:
    - Each step should be a single, concrete action.
    - Steps should be in execution order.
    - 3-10 steps is ideal. Fewer for simple tasks, more for complex ones.
    - Do not include explanations, markdown, or any text outside the JSON.
    """
}